namespace SteamServerManager.Processing.Delegates;

/// <summary>
/// Represents an event that handles output data generated by a process.
/// </summary>
/// <param name="data">The output data produced by the process.</param>
public delegate void ProcessOutputHandler(string data);